Admin Dash Board Product 조회 및 Item 조회, 추가, 변경, 삭제 기능 구현
casually-sogong/jpetstore-6 pull request #14
Opened 2022-12-01 14:39 UTC by rossssa

관리자와 일반 유저를 나누어 관리자만 사용할 수 있는 기능인 Dash Board Product 조회 및 Item 조회, 추가, 변경, 삭제 기능 구현을 구현하였습니다.

2022-12-03 09:09 UTC, Tekiter approved these changes

2022-12-03 09:26 UTC, Tekiter requested changes
AdminService를 삭제하고, 관련 함수들은 역할에 맞는 다른 Service 클래스로 이동시켜주세요.

2022-12-03 09:26 UTC, Tekiter commented on src/main/webapp/WEB-INF/jsp/admin/ItemList.jsp
> +    </c:if>
어드민으로 접속할 수 있는지 판정을 jsp단이 아니라 ActionBean 단에서 하도록 바꿔주세요.

401.jsp 파일을 만들고 AdminActionBean에 `private static final String PAGE_401 = "/WEB-INF/jsp/401.jsp"`를 추가한 다음에, AdminActionBean 의 view 함수들에서 어드민인지 판정하고 만약 어드민이 아니라면 `return new ForwardResolution(PAGE_401)` 해서 다른 jsp를 보여주도록 바꾸는 것이 이상적일 것 같아요.

2022-12-03 09:49 UTC, Tekiter commented on src/main/webapp/WEB-INF/jsp/common/IncludeTop.jsp
> +<div id="Content"><stripes:messages /></div>
```suggestion
<div id="Content"><stripes:messages />
```

불필요한 닫기 태그로 레이아웃이 깨지네요. 이 div는 `IncludeBottom.jsp` 에서 닫고있어요.

2022-12-04 06:33 UTC, marinesnow34 approved these changes

2022-12-04 07:50 UTC, Tekiter requested changes
빌드 오류가 나네요. 다시 확인해주세요!
<img width="590" alt="image" src="https://user-images.githubusercontent.com/36122585/205480055-362f22ef-025d-4125-bcf4-4f9e06065e10.png">

2022-12-04 14:53 UTC, Tekiter approved these changes

2022-12-04 14:54 UTC, merged